modified
quest-academia/laravel-posts-training pull request #1
Opened 2021-02-04 05:03 UTC by Akrjourney

以下を修正致しました。
ご確認よろしくお願い致します。

・POST編集画面でもヘッダー・フッターを表示
⇨投稿画面にヘッダー、・フッターをつけ忘れていました。
　修正後、再度プルリクさせていただきます。

・フッターを「©2021 QuestAcademia, All rights reserved.」に変更

・POST編集画面で編集前のタイトル・本文が表示されるように

・画面幅を小さくしたときに右上のメニューがクリックできなくなる点の修正

・投稿時刻は記載なしに変更
⇨こちらは記事投稿・コメントとも投稿時刻なしで宜しかったでしょうか？

2021-02-05 14:36 UTC, quest-academia requested changes
修正ありがとうございました！

今回修正頂いた内容、ほぼ完璧です✨

ログイン失敗時の文言についてGitHubに記述しておりますので、修正をお願い致します😊
それができたらこのブランチはマージさせていただだきます。

引き続き、宜しくお願い致します！

2021-02-05 14:36 UTC, quest-academia commented on resources/views/navbar.blade.php
>              <li>
レスポンシブ良い感じですね😊
修正ありがとうございます！

2021-02-05 14:36 UTC, quest-academia commented on resources/lang/ja/auth.php
> +    'failed' => 'ログイン情報が登録されていません。',
メールが一致していても

「ログイン情報が登録されていません」

と出て、これは文言としておかしいので、

「認証に失敗しました。」

に変更しましょう！

2021-02-05 14:36 UTC, quest-academia commented on resources/lang/ja/validation.php
> +    'dimensions'           => ':attributeの図形サイズが正しくありません。',
ありがとうございます！

ちゃんとバリデーション日本語化できていて素晴らしいです😊

2021-02-06 23:09 UTC, SekiYukihiro approved these changes
・POST編集画面で編集前のタイトル・本文が表示されるように変更
⇨前回POST投稿画面にヘッダー・フッターをつけるのを忘れていたので、今回修正しております。
➡️　OKです😊

・コメント投稿の際も投稿ボタンを押して投稿できるように変更
⇨先ほど修正致しました。今回のプルリクで修正が反映されていると思います。
　コメント欄の見た目や、ボタンの位置など気になる点があれば仰ってください。
➡️　ありがとうございます！
　　見た目に関しては、気になる点はあるのですが、先に機能的な修正を優先して頂こうと思いますので、
　　一旦はこれでマージいたします✨

・ログイン失敗時の文言を修正
⇨「認証に失敗しました」に変更しています。
➡️　OKです！

・/users/editのユーザ情報変更ページ
⇨パスワード変更時に、パスワードを非表示にするよう設定し直しました。
➡️　OKです！

・「編集」「削除」ボタンの位置を変更
⇨コメントボタンも入れるとなると、ボタンが増えて見にくくなるかと思いまして、
位置を変更させていただきました。
➡️　確かに、今の位置の方がいいですね！お気遣いありがとうございます😊


全体的に問題ないので、マージしました！
ありがとうございました！

2021-02-06 23:11 UTC, quest-academia approved these changes

2021-02-06 23:12 UTC, merged