投稿一覧画面、PostsIndexの編集
quest-academia/laravel-posts-training pull request #11
Opened 2021-03-09 09:13 UTC by Soya0719

投稿一覧画面です。
ご確認のほど、よろしくお願いします。

2021-03-17 10:31 UTC, Soya0719 commented
ご確認のほど、よろしくお願いします。

2021-03-19 05:01 UTC, KyoheiYamamoto requested changes
大変遅くなり申し訳ございません・・・
確認しました。

修正点が多数ございますのでご確認よろしくお願いします。
また、foreach文の仕組みを一度ググってみてみるのと
プルリクあげる前には必ずテストして動作確認をするようによろしくお願いします。

2021-03-19 11:56 UTC, Soya0719 commented
PostContoller,footer,header,indexの修正を行いました。ご確認のほど、よろしくお願いします。

2021-03-19 13:14 UTC, KyoheiYamamoto requested changes
確認しました！
指摘している部分を修正して動作確認してからpushよろしくお願いします。

2021-03-19 13:14 UTC, KyoheiYamamoto commented on resources/views/posts/index.blade.php
> -                <h2>Post title</h2>
ビューでコントローラーの値を表示させるためにそれぞれ「h2タグ」の中身を
Post titleではなくSeederに格納されているtitleのカラムを呼び出してください

2021-03-19 13:14 UTC, KyoheiYamamoto commented on resources/views/posts/index.blade.php
> -                <p class="card-text">Post body</p>
ビューでコントローラーの値を表示させるためにそれぞれ「pタグ」の中身を
Post bodyではなくSeederに格納されているbodyのカラムを呼び出してください

2021-03-19 13:14 UTC, KyoheiYamamoto commented on resources/views/posts/index.blade.php
> -                <span>投稿日時:2020-1-1</span>
ここはcreated_atで呼び出してください

2021-03-21 16:22 UTC, Soya0719 commented
アドバイスの通り、PostsController.php,PostsTableSeeder.php,Index.blade.phpの修正を行いました。ご確認のほどよろしくお願いします。

2021-03-22 01:50 UTC, KyoheiYamamoto reviewed
確認しました！！アドバイスを忠実にやった結果私の方でも問題なく動きました！！
スタイルのずれがあったのでそこを指摘していますのでご確認くださいませ
修正したら僕にslackで通知次第merge しましたとコメントがきましたら。次にお進みくださいませ〜

2021-03-22 01:50 UTC, KyoheiYamamoto commented on resources/views/posts/index.blade.php
> +    </div>
インデントはちゃんと整えた方が良いです！！

2021-03-22 01:50 UTC, KyoheiYamamoto commented on resources/views/posts/index.blade.php
> +
```<div class="card mb-4">```に対しての閉じタグ</div> がないのでスタイルがずれていると思います

2021-03-22 13:44 UTC, Soya0719 commented
index.blade.phpのインデントとタグを閉じる修正をしました。
マージを行い次に進みます。

2021-03-22 13:51 UTC, KyoheiYamamoto commented
動作確認してインデントがずれていなかったのと
スタイルが正常に動いていたので問題ないので次にお進みくださいませ〜

2021-03-22 13:52 UTC, merged