add: Seederの内容記述
quest-academia/laravel-posts-training pull request #113
Opened 2021-05-06 06:14 UTC by Naoya0125

お疲れ様です。
アドバイスいただきましたSeederの中身を記述しております。

その後　php artisan db:seed --class=UsersTableSeeder　で確認をしました。

どうぞご確認のほどよろしくお願いいたします。

2021-05-06 06:37 UTC, hsg0830 requested changes
質問への回答です。

2021-05-06 06:37 UTC, hsg0830 commented on database/seeds/UsesTableSeeder.php
> +class UsesTableSeeder extends Seeder
ご質問の件ですが、ファイルの名前ではなく、ここのクラス名がどうなっているかに関係してきます。
`DatabaseSeeder.php`では、`$this->call(UsersTableSeeder::class);`としているのに、そんなクラスないぞ！と蹴られちゃうからですね。
よかったら、こちらクラス名を修正してもう一度試してみてください。

2021-05-06 06:43 UTC, hsg0830 requested changes
分からないことがありましたら、Slackで質問してくださいね。

2021-05-06 06:43 UTC, hsg0830 commented on database/seeds/UsesTableSeeder.php
> +    }
- この方法もありですが、複数件登録するのに冗長になりますし、仮にダミーデータが100件とか要るとなった場合、これだとかなり大変なので、for文などを使ってダミーデータを登録するといいですね。
- これだと、おそらく`created_at`と`updated_at`のカラムがNullになってしまうかと思うので、`'created_at' => now()`とかで登録されるようにするといいですね。

2021-05-07 11:28 UTC, Naoya0125 commented on database/seeds/UsesTableSeeder.php
> +    }
database/seeds/UsersTableSeeder.php

@hsg0830 
お疲れ様です！
slackにてご確認ありがとうございました。
UserTableSeederを訂正しましたので、ご確認のほどよろしくお願いいたします。
どうぞよろしくお願いいたします。

2021-05-07 11:39 UTC, merged