add:新規登録画面の実装 #91
quest-academia/laravel-posts-training pull request #124
Opened 2021-05-08 14:06 UTC by Naoya0125

お疲れ様です。
新規登録画面の実装ができましたので、ご確認の程よろしくお願いいたします。

やったこと
•`register.blade.php`の作成、中身の記述
•`error_card_list.blade.php`の作成、中身の記述
•`app.blade.php`中身の記述

編集したところ
•`web.php`に以下を追加
```
Route::get('signup', 'Auth\RegisterController@showRegistrationForm')->name('signup');
Route::post('signup', 'Auth\RegisterController@register')->name('signup.post');
```
•`RegisterController.php`にてリダイレクト先を`home`から`= '/';`に変更。

こちらの記載方法で問題ないでしょうか。
お忙しいところ恐れ入りますが、ご確認のほど、どうぞよろしくお願いいたします。

2021-05-09 01:07 UTC, hsg0830 requested changes
お疲れ様です！

基本的な実装は問題なくできているようですね！
エラーもMTGで解決できたようで何よりです〜^^

一点だけ、細かい修正で申し訳ないのですが、
現状、`app/Http/Middleware/RedirectIfAuthenticated.php`により、
既にログインしてる人が`signup`などにアクセスしようとすると別ページに飛ばすようになっていますが、
そこの飛ばし先が、↓のように`redirect('/home')'となっていて、404エラーとなります。
こちらでもトップページに　リダイレクトさせるように変更するといいかもしれません。
https://gyazo.com/c8ad49a403cab99371807412791505b1

※デフォルトでは、新規登録と同時に、ログイン状態になるようになっています。
　ですので、一度新規登録した後に、もう一度`/signup`を叩くと、
　404となると思います。

下に付したコメントはあくまでご参考程度に書いてものなので、
修正の必要はありません^^

2021-05-09 06:27 UTC, Naoya0125 commented on app/Http/Middleware/TrustProxies.php
> +    protected $proxies = '*';
@hsg0830 
HANさん　
お疲れ様です！
レビューいただきありがとうございます！
トップページへリダイレクトするように変更いたしました。

いつも詳細なところまで見ていただきありがとうございます😊
どうぞ今後ともよろしくお願いいたします。

2021-05-09 08:02 UTC, hsg0830 commented
@Naoya0125 

リダイレクトの修正、確認いたしました！

先ほどは、ログアウトができず確認しそびれていた点が一点ありまして…。

登録機能自体は問題なく実装できているようですが、
登録用のブレードのレイアウトが崩れてしまっているようです。

https://gyazo.com/cfb2c257813d70a3648639dea913a8b3

細かい修正で申し訳ありませんが、
今一度確認いただけますでしょうか？

よろしくお願いします！

2021-05-09 08:52 UTC, Naoya0125 commented
@hsg0830 

お疲れさまです！
レイアウトの部分完全に見落としていました💦
ご確認いただきありがとうございます🙇‍♂️

中央に来るようにレイアウト修正をいたしましたので、お手数おかけしますが再度ご確認のほどよろしくお願いいたします🙇‍♂️

2021-05-10 02:55 UTC, hsg0830 commented
@Naoya0125 

お疲れ様です！
センタリングはしっかりできていますね！

ただ、Paddingなどがモックアップと違っているような気がします…。

https://gyazo.com/392be3e2c53dd1adb4d72812a1b5b1d4

↑で左がサンプル、右がNaoyaさんのものなのですが、
Paddingが無くきゅうきゅうに詰まってしまっていないでしょうか？

見た目部分の調整は細かくて面倒くさいところではありますが、
印象を左右する大事な部分だと思われますので、
完璧にサンプルに揃える必要はありませんが、
少し調整してみていただければいいかなぁと思います。

お手数ですがよろしくお願いします！

2021-05-10 08:46 UTC, Naoya0125 commented
@hsg0830 

お疲れさまです！
先程はありがとうございました。
ご確認いただきました新規登録画面でのレイアウトを変更しました。
このようなレイアウトでよろしいでしょうか？

お手数おかけしますが、ご確認のほどよろしくお願いいたします。

2021-05-10 14:10 UTC, merged