個人課題：新規投稿画面の完了(nao)
quest-academia/laravel-posts-training pull request #13
Opened 2021-03-15 12:51 UTC by nao-fujimura-09

個人課題の新規投稿画面が完了しました。
よろしくお願い致します。

2021-03-15 23:21 UTC, KyoheiYamamoto requested changes
細かい修正点がありますのでご確認くださいませ〜
一旦削除処理はまだまだ実装は先なので一旦コメントアウトしておいた方が
良いかもですね〜

2021-03-15 23:21 UTC, KyoheiYamamoto commented on routes/web.php
> +Route::delete('/show/{posts_id}', 'PostsController@destroy')->name('posts.delete');
こちらも記載間違っているのでいったん削除処理の時までコメントアウトしておきましょうか

2021-03-15 23:21 UTC, KyoheiYamamoto commented on resources/views/posts/create.blade.php
> +        {!!Form::submit('投稿する', ['class'=>'btn btn-primary'])!!}
これ、editの処理ではちゃんとできているじゃないですかｗｗｗ

2021-03-16 08:56 UTC, nao-fujimura-09 commented on resources/views/posts/create.blade.php
> +        {!!Form::submit('投稿する', ['class'=>'btn btn-primary'])!!}
laravelの記事を見直してたのですが関係ないとこだと思って見逃してしまってたのが間違えている原因でした😭

2021-03-16 23:38 UTC, KyoheiYamamoto reviewed
OKです！！こちらmergeしておきますね〜
課題５の編集画面だけ実装はできているので
課題6のバリデーションと更新処理を頑張ってくださいね

2021-03-16 23:38 UTC, merged