add:ログイン機能の実装
quest-academia/laravel-posts-training pull request #134
Opened 2021-05-12 04:15 UTC by Naoya0125

お疲れ様です。  
ユーザーログイン画面の実装ができましたので、ご確認の程よろしくお願いいたします。

やったこと  
•login.blade.phpの作成、中身の記述  

編集したところ  
•web.phpに以下を追加
Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login','Auth\LoginController@login')->name('login.post');
Route::get('logout','Auth\LogoutController@logout')->name('logout');

こちらの記載方法で問題ないでしょうか。  
お忙しいところ恐れ入りますが、ご確認のほど、どうぞよろしくお願いいたします。

2021-05-13 00:52 UTC, hsg0830 requested changes
まずは、どのコントローラーを指定すべきか確認し、ログインした状態で、`/logout`にGETリクエストを送った場合(ブラウザでURLの後ろに/logoutと入力しエンターを押した場合)にログアウトができるようにしてみてくださいね。

ログアウトをPOSTにする件などは、また改めてSlackでご質問頂ければと思います。

頑張ってくださいね！^^

2021-05-13 00:52 UTC, hsg0830 commented on routes/web.php
> +Route::get('logout','Auth\LogoutController@logout')->name('logout');
- こちら、`LogoutController`などは存在しないため、ログインしている状態で、`/logout`を叩くとエラーが出るかと思います。現状用意されているコントローラーは↓だけなので、ここのどこで、`logoutというアクション`が書かれているかを探してみて、修正してみてくださいね。

https://gyazo.com/d69fdb8eac2fb1b48641f2dd48101157

- 現段階では、ログアウト機能は実装の対象範囲ではないのかもしれませんので、テスト的にログアウトできるようにするだけであれば、今のように`GET`で大丈夫ですが、本来ログアウトは、リクエストを送って、現在のセッションを破壊するなどの変化を加える処理ですので、実際は`POST`にするのが一般的です。

2021-05-13 07:36 UTC, Naoya0125 commented on routes/web.php
> +Route::get('logout','Auth\LogoutController@logout')->name('logout');
@hsg0830 

お疲れ様です！
すみません、こちらでのコメント返信が漏れていました…
ご教示いただきました、ログインをしている状態から/logoutを叩くとログアウトし、welcome.bladeの画面に戻るように修正をしてみたのですが、こちらであっていますでしょうか…？

どうぞご確認のほどよろしくお願い致します。

2021-05-14 02:12 UTC, hsg0830 commented on routes/web.php
> +Route::get('logout','Auth\LogoutController@logout')->name('logout');
@Naoya0125 

お疲れ様です！
確認が遅くなってすみません！

そうですね。ひとまずはこれでいいと思います。

今後、実際にログアウトのボタンを設置する段階では、
`POST`送信に変更してくださいね！

2021-05-14 02:13 UTC, merged