コメント投稿機能作成。 #84
quest-academia/laravel-posts-training pull request #143
Opened 2021-05-13 15:27 UTC by Hikaru-Giannis

お疲れ様です！

やったこと
- コメント投稿アクション作成。
- コメント投稿バリデーションファイル作成。
- コメント投稿フォーム作成。
- コメント投稿アクションへのルーティングを追加。

考慮して欲しいこと
- 仰っていた通りバリデーションに苦労し、配列の`$key`を`hidden`で渡すか`post_id`で実装するか悩みましたが、余計なパラメータを渡したくなかったので`post_id`で実装させていただきました。
- コメント投稿フォームが少し冗長になるかなと思われたので別途`include`するように実装しました。

確認のほどお願いします。

2021-05-14 04:01 UTC, hsg0830 requested changes
@Hikaru-Giannis 

お疲れ様です！

初めてでは難しい実装もあったかと思いますが、素晴らしいですね！！

基本的には全然OKで、一応、思ったことをコメントとして残しておきましたので、ご検討ください。

2021-05-14 13:14 UTC, Hikaru-Giannis commented
お疲れ様です！
レビューしていただきありがとうございます！

やったこと
- コメント投稿に認証middlewareを挟むように修正。
- `user_id`をhiddenではなく、コントローラーの`Auth::id()`で取得するように修正。
- commentの配列のキーがpost_idと一致するかの検証を追加。
- コメント投稿フォームにおいて、`user_id`の`hidden`箇所を削除。

考慮して欲しいこと

> app.blade.phpに組み込まれているエラーメッセージ表示の部分と重複して2個エラーがでる

上記に関して、かずやさん側の実装との問題だったので、エラーを共有しかずやさんの方で微調整の時に各bladeファイルで読み込むように修正を依頼しておきました。

確認のほどお願いします。

2021-05-15 00:35 UTC, hsg0830 requested changes
お疲れ様です！ミドルウェアを挟むことで、比較的シンプルな実装になったのではないかと思います！^^
`post_id`の整合性の件、実際ユーザーの操作対象ではないので、バリデーションに含めるかどうかは考えものかもしれませんが、ご検討ください^^

2021-05-15 00:35 UTC, hsg0830 commented on app/Http/Controllers/CommentsController.php
> +        }
こういうチェックを取り入れるのは、一手間ですけど良いと思いますよ！

- ただ、現状`return`が無いので、機能していないようですね…。

- また、不一致だった場合に弾きたいので、`!=`ではないでしょうか？

2021-05-15 00:35 UTC, hsg0830 commented on app/Http/Requests/CommentStoreRequest.php
> +            'comment.*' => ['required','max:40']
現在、コントローラーで整合性のチェックはしていますが、リダイレクトするだけで。エラーがなどが表示されないというのもあるので、エラーメッセージを返したり、そもそもバリデーション段階でもチェックするといことになれば、っここの28行目を、`'comment.' . $this->post_id`のように変えてもいけるんじゃないかと思います！^^

2021-05-15 00:35 UTC, hsg0830 commented on resources/views/layouts/comment_error_card_list.blade.php
> +@endif
この件、了解です！

2021-05-15 00:35 UTC, hsg0830 commented on routes/web.php
> +    });
これでOKですね！
人によっては、さらにコントローラーのコンストラクタにもミドルウェアを挟んだりするようです^^
流儀による、って感じもありますが、何重にもセキュリティ対策するみたいな感じですかね。
ひとまずこれだけでいいと思いますので、ご参考までに。

2021-05-15 01:56 UTC, Hikaru-Giannis commented on routes/web.php
> +    });
そうなんですね！今後の参考にさせて頂きます！

2021-05-15 01:57 UTC, Hikaru-Giannis commented
お疲れ様です！
レビューしていただきありがとうございます！

やったこと
- 整合性チェックのカスタムルールを追加。

少し冗長になってしまったかもしれませんが、今後もバリデーション

2021-05-15 02:00 UTC, Hikaru-Giannis commented on app/Http/Controllers/CommentsController.php
> +        }
失礼しました...。おっしゃる通りです！
コメントが投稿されているのは確認はしたのですが、機能していないことを考慮しておりませんでした...。

2021-05-15 05:49 UTC, hsg0830 requested changes
@Hikaru-Giannis 

お疲れ様です！
さすが現役PHPエンジニアなだけあって、
色々な機能を把握、駆使されていて素晴らしいですね！！

一点だけ修正した方がいいかな、と思う箇所を記しましたので、
ご検討ください^^

2021-05-15 05:49 UTC, hsg0830 commented on app/Http/Requests/CommentStoreRequest.php
> +            'comment.'.$this->post_id => ['required', 'max:40', new CommentKeyCheck($this->post_id)]
ここで、`'comment.'.$this->post_id`の方を使うと、
せっかく独自ルールを作ってメッセージを変更したのに、
ここのバリデーションで必ず引っかかって、
コメントを入力したのにもかかわらず、
`コメントは必須です。`というメッセージの方が表示されてしまいますね。
ユーザーに親切なメッセージが表示されるようにRuleを作ってくださったので、
こちら側は、`'comment.*`の方がいいかもですね！

2021-05-15 06:04 UTC, Hikaru-Giannis commented on app/Http/Requests/CommentStoreRequest.php
> +            'comment.'.$this->post_id => ['required', 'max:40', new CommentKeyCheck($this->post_id)]
ありがとうございます！
確かにそうですね...。
上記を参考に修正させていただきます。

2021-05-15 15:00 UTC, SekiYukihiro requested changes
全体的によく考えられたと思います😊

よりよくするには、という点での指摘を書かせていただきましたので、
参考にしてご変更いただければと思います。

お手数ですが、宜しくお願い致します！

2021-05-16 01:04 UTC, Hikaru-Giannis commented on app/Http/Requests/CommentStoreRequest.php
> +            'comment.*' => ['required', 'max:40', new CommentKeyCheck($this->post_id)]
バリデーションをカスタムする方法でも色々あるんですね...。
是非参考にさせていただきます！

2021-05-16 01:09 UTC, Hikaru-Giannis commented on app/Rules/CommentKeyCheck.php
> +        return $keys[1] == $this->post_id;
承知しました！
この辺に関しては個人だと気づけなかったり、
頭で理解しててもテキストで説明するのに苦労することが多いので、
なるべく今後も意識して頑張ります。

2021-05-16 02:57 UTC, SekiYukihiro approved these changes
良くなったと思います！
変数名もシンプルにわかりやすい$commentKeysで良いと思いますよ！
問題ないのでマージしますね☺️

僕が今までいた現場では、詳しめにコメントを書く場合が多かったので
僕ならこんな書き方ですかね。

```
　　 // $attributeは文字列の"comment.添字"であるため、ドット区切りで配列化
        $commentKeys = explode('.', $attribute);
        // commentの配列の添字がpost_idと一致するか検証
        return $commentKeys[1] == $this->post_id;
```

良ければ、参考にしてみて下さい。

2021-05-16 02:57 UTC, SekiYukihiro commented on app/Rules/CommentKeyCheck.php
> +        return $commentKeys[1] == $this->post_id;
良くなったと思います！
変数名もシンプルにわかりやすい$commentKeysで良いと思いますよ！
問題ないのでマージしますね☺️

僕が今までいた現場では、詳しめにコメントを書く場合が多かったので
僕ならこんな書き方ですかね。

```
　　 // $attributeは文字列の"comment.添字"であるため、ドット区切りで配列化
        $commentKeys = explode('.', $attribute);
        // commentの配列の添字がpost_idと一致するか検証
        return $commentKeys[1] == $this->post_id;
```

良ければ、参考にしてみて下さい。

2021-05-16 02:58 UTC, merged