add:posts(投稿)テーブルのマイグレーションとシーダー作成　#166
quest-academia/laravel-posts-training pull request #182
Opened 2021-06-09 15:20 UTC by sukapontan

migrationファイルとseederファイルを新規作成しました。
また、その他マイグレーションの実行のためapp/Porviders/AppserviceProvider.phpなども必要に応じて変更しております。
ブランチ名やその他の命名規則などで不備がありましたらご指摘ください。

お手数ですがご確認宜しくお願い致します。

2021-06-09 22:53 UTC, sukapontan commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +            $table->bigIncrements('id');
こちらの主キーのデフォルトがbigIncrementsになっていたのですが、教材と同様にincrementsに変更した方がよろしいでしょうか？
ご確認宜しくお願い致します。

2021-06-10 01:32 UTC, hsg0830 requested changes
@sukapontan 

お疲れ様です！
プルリクまで色々と大変な点もあったかと思います。

今書かれているコード自体は間違っていないのですが、
少し手を加えていく必要がありそうなので、
コメントを残しておきました。

ご確認くださいね。

2021-06-10 01:32 UTC, hsg0830 commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +            $table->bigIncrements('id');
`increments`も`bigIncrements`も、符号なしのない数値型を使用した自動増分IDのカラムを作ってくれる点では同じですが、`increments`だと`INT型`、`bigIncrements`だと`BIGINT型`になるという違いがありますね。両者は、表せる数字の範囲が異なり、そのことから、データ量に違いが生じ、記憶領域の消費や処理時間などで違いが出てくる感じですね。（https://e-words.jp/w/BIGINT%E5%9E%8B.html）

どちらでもOKですが、このテーブルのレコードはそんなに増えない、つまりIDがそんなに増加しない、というテーブルなら、INT型になる`increments`でもOKだと思います。

ただ、Laravel8とかには、`$table->id();`というのができており、これは`$table->bigIncrements('id');`と同じです。デフォルトで、`bigIncrements`を使ってる感じですね。なので迷ったら、idは`bigIncrements`にする、でもいいかもです。
外部キー制約をつける際などは、関係付けるカラムどうしの型も同じでなければならないので、こっちはINT型、こっちはBIGINT型と状況に応じて使い分けると、逆にややこしくなることもあるかもしれませんね。

2021-06-10 01:32 UTC, hsg0830 commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +            $table->timestamps();
・細かい指摘で恐縮ですが、インデントは揃えることを習慣にしてくださいね！インデントが揃っているかいないかだけで、コードを見た時の印象が左右され、それが色々なことに影響してくるので^^;

・`title`は「50文字以内」という制限を設ける必要があったはずなんですが、仕様の方はどうなってますでしょうか？僕が仕様のドキュメントを見つけられず、記憶を頼りに書いちゃってます^^;


・まだ、ユーザー周りの実装も始まったばかりなので、後々そことの調整は出てくると思いますが、「誰が投稿したものか」の情報を格納するためのカラムを、この時点で作っておいてもいいかと思います。その際は、usersテーブルとどのような関係になるのか、どのようなカラムを設けるべきか、検討してみてくださいね。

2021-06-10 01:32 UTC, hsg0830 commented on database/seeds/PostsTableSeeder.php
> +        ]);
・ここも、インデントは揃えてみてくださいね。

・あと、この書き方でも問題ないのですが、今の書き方だと同じことを何度も書いていて冗長な感がありますね。また、実務で100件分のダミーデータを入れたいとなった場合、この書き方だとかなり大変ですよね。なので、ループ処理をするなどして、より短くすっきり、かつ件数が増えてもすぐに対応できる書き方を考えてみるのがいいかもしれません。

・上のマイグレーションのところで書いた内容に関係しますが、誰の投稿かに関する内容を追加したら、こちらでもそれに関する情報を追加する必要がありますね。

2021-06-10 13:13 UTC, sukapontan commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +            $table->timestamps();
＞細かい指摘で恐縮ですが、インデントは揃えることを習慣にしてくださいね
インデントについて確認不足で申し訳ございません。
インデントをそろえることを徹底いたします！

＞titleは「50文字以内」という制限を設ける必要があったはずなんですが、仕様の方はどうなってますでしょうか？
こちら、私の方でも仕様のドキュメントがどこにあるかわからず…。slackの方で確認いたします。

＞「誰が投稿したものか」の情報を格納するためのカラムを、この時点で作っておいてもいいかと思います。
こちら、考慮不足で申し訳ございません。再度、よく考えて実装し直します。

2021-06-10 13:15 UTC, sukapontan commented on database/seeds/PostsTableSeeder.php
> +        ]);
こちらでもインデント失礼いたしました。

シーダーに関して、ループ処理での実装に変更して修正いたします。
ご指摘いただき、ありがとうございます！

2021-06-12 07:39 UTC, sukapontan commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +	        $table->string('title', 50);
ご指摘いただいた50文字の入力制限とuserテーブルとの紐づけにuser_idカラムの追加も致しましたが、こちらだけでは情報不足でしょうか？
また、コメントとの紐づけも必要だったでしょうか？
知識不足で大変申し訳ありませんが、考慮不足などあればご指摘ください。

2021-06-12 07:40 UTC, sukapontan commented on database/seeds/PostsTableSeeder.php
> +
シーダーでのテストデータ作成もループ処理に変更いたしました。
こちらも考慮不足あればご指摘ください。

2021-06-12 08:12 UTC, sukapontan commented on database/seeds/PostsTableSeeder.php
> +                'user_id' => $i,
マイグレーションで追加したuser_idカラムの追記を失念しておりました。
動作確認を怠っており、大変申し訳ありませんでした。
ご確認宜しくお願いいたします。

2021-06-13 02:11 UTC, hsg0830 commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +    }
`user_id`カラムに入り得るものは、`users`テーブルの`id`カラムに存在する数値でなければならないと思います。データベース内でそのような整合性を保つために用いるのが、`外部キー制約`です。ここでも、そのような内容の外部キー制約をつけてあげる必要がありそうですね。

`$table->foreign('user_id')->references('id')->on('users');`のように書くと、
今作ろうとしている`user_id`というカラムに入り得る内容は、
`users`テーブルの`id`に存在する値じゃなきゃダメだよ、
という制約をかけられます。
この点についてご不明な点などあれば、調べたり質問したりしてくださいね！

2021-06-13 02:11 UTC, hsg0830 commented on database/seeds/PostsTableSeeder.php
> +                'user_id' => $i,
Fakerも用いて、ループを用いてすっきり書き換えられてすごくいいですね！

2021-06-13 02:11 UTC, hsg0830 commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +	        $table->string('title', 50);
コメントとの紐付けは、コメント側でやることになると思いますよ〜

2021-06-13 02:13 UTC, hsg0830 requested changes
色々と研究して修正されていて、大変素晴らしいですね！
もう少しだけ手を加える必要がありそうなので、
コメントを残しておきました。
ご確認くださいね。

2021-06-13 06:13 UTC, sukapontan commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +            $table->bigInteger('user_id')->unsigned();
こちらに関しては小野さんの開発したusersテーブルを確認し、bigIncrementで定義されていたのでbigIntegerにいたしました。
またunsigned()でマイナスの値と許容しないようにいたしました。
確認ですが、->index()は不要で問題ないでしょうか？
投稿に検索などの機能はないので不要かと思い、記載しておりませんが必要でしたらご指摘ください。

2021-06-13 06:17 UTC, hsg0830 approved these changes

2021-06-13 06:17 UTC, sukapontan commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +            $table->foreign('user_id')->references('id')->on('users');
こちらに外部キー制約を追記し、usersテーブルのidと紐づけて制約を掛けました。
HANさんからご教示いただいたものをそのまま使用してしまっていますが、問題ないでしょうか？
また、この制約を設けたことにより、php artisan db:seedを実行すると「 SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails 」とエラーが発生しますが、現状はusersテーブルが存在しないため、発生しているのかと思います。
こちらも何か修正が必要なのでしょうか？

2021-06-14 00:24 UTC, hsg0830 requested changes
お疲れ様です！
コンフリクトも解消できていて素晴らしいですね！

ほぼ仕上がってきていますが、コメントを残しておいたので、もう少しだけ修正してみてくださいね。

2021-06-14 00:24 UTC, hsg0830 commented on database/seeds/DatabaseSeeder.php
> +        $this->call(UsersTableSeeder::class);
シーディングでデータを入れる場合に、仮にpostsテーブルでusersテーブルのidを参照したい場合、usersテーブルに先にデータが入っている必要がありますね。ですので、シーディングの順番は逆にしたほうがいいですね。

2021-06-14 00:24 UTC, hsg0830 commented on database/seeds/PostsTableSeeder.php
> +                //'user_id' => $i,
user_idはnullは許容しないはずなので、usersテーブルにデータがない場合、こちらでは、例えば1〜3までの数字がランダムに入るようにするなどして、なんらかの値を入れてあげる必要がありますね。
逆に、コメントアウトすべきは、ここではなく、マイグレーションで外部キー制約をつけている箇所になりますね。

2021-06-14 11:23 UTC, sukapontan commented on database/migrations/2021_06_09_205043_create_posts_table.php
> +            //$table->foreign('user_id')->references('id')->on('users');
マイグレーションファイルの外部キー制約を一時的にコメントアウトいたしました。
usersテーブルとの連携が取れましたらコメントアウトを解除いたします。

2021-06-14 11:24 UTC, sukapontan commented on database/seeds/PostsTableSeeder.php
> +                'user_id' => $i,
理解が浅くて申し訳ありません。
user_idはnullを許容していないのでこちらはコメントアウトを解除しました。

2021-06-14 11:25 UTC, sukapontan commented on database/seeds/DatabaseSeeder.php
> +        $this->call(PostsTableSeeder::class);
UsersTableSeederが先に実行されるように変更いたしました。
データベース周りの知識も浅すぎるのでしっかりと勉強しておきます。

2021-06-15 05:11 UTC, hsg0830 approved these changes

2021-06-15 05:12 UTC, merged