コメントのvalidation修正
quest-academia/laravel-posts-training pull request #2
Opened 2021-02-08 09:40 UTC by Akrjourney

ご指摘いただいた部分で、
「コメント欄に空文字のままでコメント送信ボタンを押すと、Laravelエラーになる」
上記の機能を一度修正してみたのですが、空コメントを送信すると全てのコメント欄の下に
エラーメッセージが表示されてしまいます。

特定のコメントに対してエラーメッセージを表示させたいのですが、他に良い実装方法が思いつかなかったこともあり、何かアドバイスをいただけると幸いです。
ご確認よろしくお願い致します。

2021-02-17 22:21 UTC, quest-academia commented on resources/views/post/index.blade.php
> +@include('common.errors')
悩まれたと思いますが、きちんとバリデーションが表示されていますね😊

ただ、エラーを繰り返し処理の中に記述されているので、
下記の写真のように、エラーが繰り返されてしまっています。
foreachの外に出しましょう！
<img width="1240" alt="スクリーンショット 2021-02-18 7 17 55" src="https://user-images.githubusercontent.com/63336345/108275555-dd435d00-71b9-11eb-8dae-296617ea25d4.png">

2021-02-17 22:45 UTC, quest-academia requested changes
とても良くなったと思います😊

いくつか修正頂きたいポイントがありますので、
お手数ですが修正頂ければと思います！

修正できましたら、言っていました通り
Herokuへのプッシュをお願いしたいと思います。

宜しくお願い致します！

2021-02-17 22:45 UTC, quest-academia commented on app/Http/Controllers/CommentsController.php
> +    $comment->comment = implode(', ', $request->input('comment'));
よくこの記述方法にたどり着かれましたね❗️
素晴らしいと思います。

上記の書き方でも問題ないのですが、記述として少し分かりにくいので
この行を下記の書き方に変更しましょう！
`$comment->comment = $request->input('comment.' . $request->post_id);`

2021-02-17 22:45 UTC, quest-academia commented on resources/views/post/index.blade.php
> +            <input name="comment[{{ $post->id }}]" value="{{ old('comment.'. $post->id) }}" class="form-control {{ $errors->has('comment') ? 'is-invalid' : '' }} comment-input border border-light" pl
この記述は今、生かされていないので、削除してOKかと思います。
`{{ $errors->has('comment') ? 'is-invalid' : '' }}`

2021-02-17 22:45 UTC, quest-academia commented on resources/views/post/index.blade.php
> +      </section>
下記の、投稿済みのコメントと、コメント入力欄の間の上下の感覚が狭いので
もう少し広げましょう！

<img width="778" alt="スクリーンショット 2021-02-18 7 42 21" src="https://user-images.githubusercontent.com/63336345/108277510-d702b000-71bc-11eb-9c67-55ddceef50d3.png">

2021-02-18 05:08 UTC, Akrjourney reviewed
ご指摘いただいた箇所を修正いたしました。
herokuにもデプロイ済です。

2021-02-18 05:08 UTC, Akrjourney commented on resources/views/post/index.blade.php
> +@include('common.errors')
こちら修正いたしました。

2021-02-18 05:29 UTC, SekiYukihiro approved these changes
OKです！

早速デプロイまでありがとうございます😊
きれいにできていますので、マージしますね！

引き続き、宜しくお願い致します❗️

2021-02-18 22:11 UTC, quest-academia approved these changes
OKです！

マージしました😊

2021-02-18 22:12 UTC, merged