Commentsテーブルを作成
quest-academia/laravel-posts-training pull request #275
Opened 2021-08-05 13:41 UTC by MionWakita

現時点では、まだ下書きの状態です。

2021-08-05 14:41 UTC, MionWakita commented on database/seeds/CommentsTableSeeder.php
> +                'content' => 'コメント1' ,
`content` という命名より、`???`というカラム名の方が適切かもしれないです。

2021-08-05 22:13 UTC, walto0903 commented on database/seeds/CommentsTableSeeder.php
> +                ]
インデントが最後だけズレている？？👀

```suggestion
            ]
```

2021-08-06 01:43 UTC, walto0903 commented on database/seeds/CommentsTableSeeder.php
> +                ]
以下で修正

2e7400e

2021-08-06 01:45 UTC, MionWakita commented on database/seeds/CommentsTableSeeder.php
> +                ]
以下で修正

2e7400e

2021-08-06 01:51 UTC, walto0903 approved these changes
データベースが[こちら](https://w1604223070-xdv436844.slack.com/archives/C02AJ2CUUAD/p1628169253003400)の設計である前提で、

LGTM‼️

2021-08-06 01:57 UTC, walto0903 requested changes
他の方のレビューを待ってマージ

2021-08-06 02:01 UTC, walto0903 approved these changes

2021-08-06 12:19 UTC, KyoheiYamamoto approved these changes
確認しました。
【今後のタスクを取り込む際で構いません】
usersテーブルとpostテーブルが作成されてmergeされた後に外部キー制約を
記述するようにしていきましょうか！！

いったんこちらはmergeします。

2021-08-06 12:19 UTC, KyoheiYamamoto commented on database/migrations/2021_08_05_222556_create_comments_table.php
> +            $table->string('content')->nullable(false);
こちらをnullabaleを記載したのはGoodです！

2021-08-06 12:19 UTC, KyoheiYamamoto commented on database/migrations/2021_08_05_222556_create_comments_table.php
> +            $table->timestamps();
【今後のタスクを取り込む際で構いません】
usersテーブルとpostテーブルが作成されてmergeされた時に外部キー制約を
記述するようにしていきましょうか！！

2021-08-06 13:12 UTC, merged