ユーザ更新画面の作成（ひかる）
quest-academia/laravel-posts-training pull request #283
Opened 2021-08-16 02:49 UTC by hikarutsujinaka

### 実装内容(What)
ユーザ更新画面のview部分の実装

### 編集したこと(Why)
viewファイル下にusersファイル作成、edit.blade.phpを追加（モックアップ参照）

### レビュワーに考慮してほしいこと
コントローラ、モデルは未実装

## 補足
特になし

2021-08-17 04:28 UTC, KyoheiYamamoto commented on app/Http/Controllers/UsersController.php
> +    }
ここの部分は編集ページに移るというながれでしょうか？？

2021-08-21 03:57 UTC, KyoheiYamamoto requested changes
ざっくりコメント入れましたが動作確認できない部分とかあったのでコメントだけ残しております・・
これって投稿の編集と削除も入れている感じでしょうか🤔

2021-08-21 03:57 UTC, KyoheiYamamoto commented on resources/views/posts/post.blade.php
> +
このファイルはコントローラーとルーティング設定していないので現状では見れないですね笑
あと、細かいんですがファイル名はなるべくどんな処理をするのかをファイル名にしたら良いかと思います🙆‍♂️
例えば新規投稿ならaddやcreate、編集ならedit、詳細ならshowとか具体的に名前付けるほうが後から見た時にわかりやすいかと思いますので名前つけるのも意識してみましょうか！

2021-08-21 03:57 UTC, KyoheiYamamoto commented on app/Http/Controllers/PostsController.php
> +         return redirect('post/index');
return redirect('post/index');を使うなら（）の中身は('/')で良い気がすますね

2021-08-21 03:57 UTC, KyoheiYamamoto commented on app/Http/Controllers/PostsController.php
> +        return redirect('post/index');
ここもすね

2021-08-21 03:57 UTC, KyoheiYamamoto commented on app/Http/Controllers/PostsController.php
> +        $post = Post::find($id);
ここfindだけだと投稿数が100しかないに1000とかになるといけないので
findOrFailを使いましょう

2021-08-21 03:57 UTC, KyoheiYamamoto commented on resources/views/posts/post.blade.php
> +        <form class="upload" id="new_post" enctype="multipart/form-data" action="{{route('posts.update',[posts,posts])}}"accept-charset="UTF-8" method="POST">
routeの中身が間違っているような気がします・・・・
現段階だとルーティングができていないのでエラーが確認できないと思います・・・笑

2021-08-21 03:57 UTC, KyoheiYamamoto commented on app/Http/Controllers/PostsController.php
> +        $post = \Auth::find($id);
ここの処理もeditと同様に```$post = Post::findOrFail($id);```が必要な気がしますね・・・笑

2021-08-23 09:04 UTC, hikarutsujinaka commented on app/Http/Controllers/PostsController.php
> +        return redirect('post/index');
承知致しました！

2021-08-23 09:04 UTC, hikarutsujinaka commented on app/Http/Controllers/PostsController.php
> +         return redirect('post/index');
承知致しました！

2021-08-23 13:33 UTC, hikarutsujinaka commented on routes/web.php
> +Route::delete('destroy/{id}', 'PostsController@destroy')->name('post.destroy');
投稿部分の削除のみでした
すみません！editとupdate部分追記いたします

2021-08-23 13:55 UTC, hikarutsujinaka commented on app/Http/Controllers/PostsController.php
> +        $post = Post::find($id);
承知致しました！

2021-08-23 13:55 UTC, hikarutsujinaka commented on app/Http/Controllers/PostsController.php
> +        $post = \Auth::find($id);
承知致しました！

2021-08-24 09:35 UTC, KyoheiYamamoto commented
コンフリクトの修正をしてください

2021-08-24 09:56 UTC, KyoheiYamamoto commented on app/Http/Controllers/PostsController.php
> +    public function edit(Post $post)
ここの（）の中身は引数やリクエストパラメータを入れるところですね・・
なので今回は$idではないかと

2021-08-24 10:29 UTC, KyoheiYamamoto commented on resources/views/users/users.blade.php
> +                    <input type="hidden" name="id" value="{{$users->id}}" />
$users じゃなくて$userだと思います・・・
他の部分の$usersになっているところは確認してください

2021-08-24 10:29 UTC, KyoheiYamamoto commented on resources/views/users/users.blade.php
> +                <form class="edit_user" enctype="multipart/form-data" action="{{('users.update',[users,users])}}" accept-charset="UTF-8" method="post">
actionの中身は{{ route('users.update', $user->id) }}かなと思います

2021-08-24 10:34 UTC, KyoheiYamamoto commented on app/Http/Controllers/UsersController.php
> +    public function edit(Request $request)
ここもすね

2021-08-24 10:41 UTC, KyoheiYamamoto commented on app/Http/Controllers/PostsController.php
> +         $user = Post::findOrFail($id);
ここの$userはどこで使われていますか？？

2021-08-24 11:23 UTC, KyoheiYamamoto commented on routes/web.php
> +Route::put('posts/{id}', 'PostsController@update')->name('post.update');
ここはpostで良いかと

2021-08-24 11:27 UTC, KyoheiYamamoto requested changes
追加で全部見ましたが全体的に動作確認できていないぽいので
次は動作確認を必ずしてからPRを出してください！！
わからない時はどこでつまづいているかを詳細に記載するようによろしくお願いいたします。

2021-08-24 11:27 UTC, KyoheiYamamoto commented on routes/web.php
> +Route::put('users/{users}', 'UsersController@update')->name('users.update');
ここもpostですね

2021-08-24 11:27 UTC, KyoheiYamamoto commented on resources/views/posts/edit.blade.php
> +        <form class="upload" id="new_post" enctype="multipart/form-data" action="{{route('posts.update',$post->id)}}"accept-charset="UTF-8" method="POST">
routeの中身が違っている感じですね・・・

2021-08-24 11:27 UTC, KyoheiYamamoto commented on resources/views/posts/edit.blade.php
> +                <input class="form-control" placeholder="タイトル" type="text" name="title" value="{{$post->title}}"/>
``` <input class="form-control" placeholder="タイトル" type="text" name="title"
     value="{{ old('title') ?? $post->title }}" />
で記載をよろしくお願いします。

2021-08-24 11:27 UTC, KyoheiYamamoto commented on resources/views/posts/edit.blade.php
> +                <textarea name="body" class="form-control" rows="10" placeholder="本文"></textarea>
ここも上記を見習ってやってください

2021-09-02 12:07 UTC, KyoheiYamamoto reviewed
いったんコメントを入れておきました！！
全体的にまだインデントがずれているので、そこの修正をよろしくお願いいたします。

2021-09-02 12:07 UTC, KyoheiYamamoto commented on resources/views/posts/edit.blade.php
> +        </div>
インデントがずれているのが気になります・・・

2021-09-02 12:07 UTC, KyoheiYamamoto commented on app/Http/Controllers/PostsController.php
> +    }
ここは改行しましょうか

2021-09-02 12:07 UTC, KyoheiYamamoto commented on app/Http/Controllers/PostsController.php
> +    public function destroy($id)
ここもですね・・

2021-09-02 12:07 UTC, KyoheiYamamoto commented on app/Http/Controllers/UsersController.php
> +     public function edit(Request $request,$id)
ここもですね

2021-09-03 09:50 UTC, KyoheiYamamoto approved these changes
ここまでお疲れ様でした。
一旦これはmergeしてcloseしますね！！次の環境構築に移動してください！！

2021-09-03 09:50 UTC, merged