Feature/ayaka/userlogin
quest-academia/laravel-posts-training pull request #284
Opened 2021-08-18 13:28 UTC by SugawaraAyaka

実装内容(What)
ログイン機能の実装
ログイン画面の作成

レビュワーに考慮してほしいこと

コードのレビューをお願いします。

補足

特になし

2021-08-19 05:07 UTC, daichi1123 reviewed
全体的にうまく書かれていると思います！

これまでは処理内容が既に用意されていましたが、自身で処理内容を書かないといけなくなり難しく感じる部分はあるかもしれませんが、頑張ってください！

一点修正点を書かせていただいているので確認よろしくお願いいたします！

2021-08-19 05:07 UTC, daichi1123 commented on resources/views/auth/login.blade.php
> +            {{ csrf_field() }}
こちら入れるのであればform内に入れるのがいいですね😄

2021-08-19 05:12 UTC, daichi1123 commented on resources/views/auth/login.blade.php
> +                ログイン
インデント入れときましょう！

2021-08-19 05:12 UTC, daichi1123 commented on resources/views/auth/login.blade.php
> +            </form>
こちらはどこで使破れている`</form>`タグでしょうか？

2021-08-19 05:38 UTC, daichi1123 requested changes

2021-08-19 05:38 UTC, daichi1123 commented on resources/views/auth/login.blade.php
> +            {{ csrf_field() }}
こちら既に`{!! Form::token() !!}`があるので必要ない様な感じがするのですが、 @SugawaraAyaka さんの環境では、11行目がないとログインできないのでしょうか？

2021-08-19 13:32 UTC, SugawaraAyaka commented on resources/views/auth/login.blade.php
> +            {{ csrf_field() }}
申し訳ありません！無くても問題なく動作しますので消去致します。

2021-08-19 13:32 UTC, SugawaraAyaka commented on resources/views/auth/login.blade.php
> +            </form>
消し忘れておりました。失礼しました。消去いたします。

2021-08-19 13:33 UTC, SugawaraAyaka commented on resources/views/auth/login.blade.php
> +                ログイン
ご指摘ありがとうございます。インデント入れさせて頂きます。

2021-08-21 02:56 UTC, KyoheiYamamoto commented
問題はないのですが、register.blade.phpの部分のログインの部分をhref属性を変更しておきましょうか

2021-08-21 11:12 UTC, SugawaraAyaka commented on resources/views/auth/login.blade.php
> +            {{ csrf_field() }}
register.blade.phpの部分のログインの部分をhref属性変更しました！

2021-08-21 12:59 UTC, daichi1123 approved these changes

2021-08-21 13:54 UTC, merged