ユーザー詳細画面を作成
quest-academia/laravel-posts-training pull request #285
Opened 2021-08-22 15:16 UTC by SugawaraAyaka

実装内容(What)
ユーザー詳細画面を作成

テスト証跡
自分自身の詳細画面と他ユーザーの詳細画面両方とも確認済み
ヘッターから詳細画面へ飛べるかも確認済み

レビュワーに考慮してほしいこと
コード、デザインの確認をお願い致します。

補足
特になし

2021-08-22 15:58 UTC, daichi1123 requested changes
しっかりとかけていると思います！
コメント残しておきましたので修正お願いいたします！

2021-08-22 15:58 UTC, daichi1123 commented on app/Http/Controllers/UsersController.php
> +use Illuminate\Support\Facades\Auth;
use は、useでまとめておきましょう！
例：
```
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\User;
```

2021-08-22 15:58 UTC, daichi1123 commented on resources/views/users/show.blade.php
> +                @if(Auth::id()===$user->id)
`@if(`
@ifと(の間に半角スペース入れておきましょう！

2021-08-22 16:04 UTC, daichi1123 commented on resources/views/users/show.blade.php
> +                    <form id="logout-form" action="" method="POST" style="display: none;">{{ csrf_field() }}
ログアウトできる様に記述お願いいたします！

2021-08-23 05:29 UTC, KyoheiYamamoto commented on app/Http/Controllers/UsersController.php
> +use Illuminate\Support\Facades\Auth;
補足すると名前空間はアルファベット順番で並べ替えるのが良いですね！！

2021-08-23 12:15 UTC, SugawaraAyaka commented on app/Http/Controllers/UsersController.php
> +use Illuminate\Support\Facades\Auth;
ありがとうございます！useでまとめました！

2021-08-23 12:16 UTC, SugawaraAyaka commented on resources/views/users/show.blade.php
> +                @if(Auth::id()===$user->id)
失礼しました！スペース入れています！

2021-08-23 12:16 UTC, SugawaraAyaka commented on resources/views/users/show.blade.php
> +                    <form id="logout-form" action="" method="POST" style="display: none;">{{ csrf_field() }}
ログアウトできるようにしました！

2021-08-24 02:35 UTC, SugawaraAyaka commented on app/Http/Controllers/UsersController.php
> +use Illuminate\Support\Facades\Auth;
すいません！アルファベット順番で並べました！

2021-08-24 07:31 UTC, daichi1123 approved these changes
とてもよくかけていると思います！

動作確認もしましたが、問題なく動作していましたので許可をいただいたのちマージさせていただきます。

2021-08-24 07:38 UTC, merged