add:PostsTableのマイグレーションとシーダーの追加
quest-academia/laravel-posts-training pull request #3
Opened 2021-02-25 16:41 UTC by Soya0719

ズームでのお話を参考にしながら、自分で調べつつ、自分が思うようにやってみました。
ご確認のほど、よろしくお願いします。

2021-02-27 14:32 UTC, KyoheiYamamoto requested changes
私の方で確認しました。
難しかったと思いますが、細かいアドバイスを送ったので修正をよろしくお願いします。

2021-02-27 14:32 UTC, KyoheiYamamoto commented on database/migrations/2021_02_26_005338_create_posts_table.php
> +            $table->char('title',20);
charでも大丈夫ですが、基本的にはPHPでは、charとvarcharとstringがあります！！
charとvarcharの違いですが、varcharがvar（可変長）＋char（文字列）＝可変長文字列であるのに対してcharは固定長なので今回はvarcharでやるのが賢明かなと思います。

varcharはLaravelでは宣言できないので、もし変更したいのであればstringで変更しましょう！！

2021-02-27 14:32 UTC, KyoheiYamamoto commented on database/seeds/PostsTableSeeder.php
> +            'text' => 'aaaaaa',
このパターンで書くとtextの部分はなるべく他の値にする方が後に楽になるので、
変更した方が賢明かなと思います

2021-02-27 14:32 UTC, KyoheiYamamoto commented on database/seeds/PostsTableSeeder.php
> +            'text' => 'aaaaaa',
このパターンで書くとtextの部分はなるべく他の値にする方が後に楽になるので、
変更した方が賢明かなと思います

2021-02-27 14:32 UTC, KyoheiYamamoto commented on database/seeds/PostsTableSeeder.php
> +            'text' => 'aaaaaa',
このパターンで書くとtextの部分はなるべく他の値にする方が後に楽になるので、
変更した方が賢明かなと思います

2021-02-27 14:32 UTC, KyoheiYamamoto commented on database/seeds/PostsTableSeeder.php
> +            'text' => 'aaaaaa',
このパターンで書くとtextの部分はなるべく他の値にする方が後に楽になるので、
変更した方が賢明かなと思います

2021-02-27 14:32 UTC, KyoheiYamamoto commented on database/migrations/2021_02_26_005338_create_posts_table.php
> +            $table->text('text');
めっちゃ細かいんですがtext('text')だと誤解しやすいのでbodyとかに変更するのが良いかと思います

2021-02-28 18:37 UTC, Soya0719 commented
マイグレーションとシーダーを変更しました。
ご確認のほど、よろしくお願いします。

2021-02-28 23:37 UTC, KyoheiYamamoto commented
指摘している点は修正できていたことを確認できました
動作確認したところマイグレーションはできていますがシーディングができていない状態です！！
一旦DatabaseSeeder.phpのクラスを追加していただき、ちゃんとマイグレーションとシーディングできたら
再度pushお願いいたします

2021-03-03 15:41 UTC, Soya0719 commented
マイグレーションとシーダーを再度編集してphpmyadminにpostsテーブルの中身が表示されるようにしました。ご確認のほど、よろしくお願いします。

2021-03-04 04:22 UTC, KyoheiYamamoto requested changes
確認しました！！
挙動はちゃんと動いていますが、より良い書き方とその理由をアドバイスとして
残していますのでご確認ください

2021-03-07 22:00 UTC, Soya0719 commented
すみません。データーベースシーダーを、推奨のされたほうに書き換えました。ご確認のほど、よろしくお願いします。

2021-03-08 00:10 UTC, KyoheiYamamoto commented
修正されているところは確認できました！！
ここからはせきさんのスライドでもあったように
下記の項目が1つ終わるごとにプッシュ→プルリク でお願いします。
次の課題に進行する際にはdevelop_fukushimaのブランチに戻って

## ①ブランチを確認
git branch // ブランチを確認するコマンド
developにいるなら手順③へスキップ
## ②develop_fukushima へ移動
git checkout develop_fukushima // developブランチに移動する
もし、この時移動できなかったら、、、
編集中のファイルがあるのが原因かと思います。
```git add .  // ワーキングツリーのファイルを全てステージングエリア（次にコミットするファイル群）へ```
```git commit -m "ここに日本語で適当なコミットメッセージを記入"```

これで編集中のファイルが全てコミットされるので、
git checkout develop で移動できます
## ③プルプル
```git pull origin develop_fukushima ```
 // リモートdevelop_fukushimaブランチの（Github上にアップされた）ファイルを取り込む

## ④自分のブランチに戻る
・まだ課題２の自分のブランチを作っていない方（ブランチ名という名前のブランチを「作って」「移動」する）
```git checkout -b ブランチ名 ```
この場合のオプション-b はブランチを新規で作るという意味です。
・既に作られていた方
```git checkout  作成したブランチ名 // 既に作ってあるブランチへ「移動」する```
```git merge develop_fukushima // ③でプルしたファイルを、自分のブランチに取り込む```

でよろしくお願いします。

2021-03-08 00:10 UTC, merged