外部キー追加
quest-academia/laravel-posts-training pull request #30
Opened 2021-03-29 04:05 UTC by Akrjourney

指摘箇所を修正しました。
user_idの部分に外部キーを追加しました。
ご確認よろしくお願いいたします。

2021-03-31 05:19 UTC, Akrjourney commented
遅くなってすみません。

・postsテーブル
・commentsテーブル
onDelete()を追加しました。
ご確認よろしくお願いいたします。

2021-03-31 05:31 UTC, SekiYukihiro approved these changes
お疲れ様です！
修正ありがとうございます！

はい、教えるのも勉強になるので
DBも是非勉強していただければと思います😊

2021-03-31 05:35 UTC, SekiYukihiro requested changes
お疲れ様です！
修正ありがとうございます！

ただ、commentテーブルはpostsテーブルに紐づくので
コメントのマイグレーションは修正が必要です！

user_idはそのままで、post_idに対して外部キー制約が付きます❗️

はい、教えるのも勉強になるので
DBも是非勉強していただければと思います😊

2021-04-04 22:17 UTC, SekiYukihiro requested changes
修正お願い致します！

2021-04-04 22:17 UTC, SekiYukihiro commented on database/migrations/2021_01_15_074449_create_comments_table.php
> +            $table->foreign('user_id')->references('id')->on('posts')->onDelete('cascade');
少々違っていて、コメントテーブルは下記の形で書いてください！
宜しくお願い致します❗️

$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
$table->foreign('post_id')->references('id')->on('posts')->onDelete('cascade');

2021-04-05 02:20 UTC, Akrjourney commented
再度修正しました！
お手数をおかけしてしまってすみませんでした。

2021-04-05 04:52 UTC, SekiYukihiro approved these changes
OKです！
マージしました！

2021-04-05 04:53 UTC, merged