指摘箇所の修正・コードのリファクタリング
quest-academia/laravel-posts-training pull request #4
Opened 2021-02-27 09:56 UTC by Akrjourney

提出が遅くなって申し訳ありません。

＜今回修正した部分＞
・app/Recipe.php / app/Admin.php / resources/views/home.blade.php / resources/views/welcome.blade.phpの削除
・resources/views/post/new.blade.php：投稿の編集　→　投稿の新規作成　へ文言を変更
・database/migrations/2021_01_15_074449_create_comments_table.php / database/migrations/2014_10_12_000000_create_users_table.php：$table->bigIncrements('id');　→　$table->increments('id');へ修正
・ユーザー、投稿、コメントのSeeder作成⇨資料を参考に作成したのですが、合っていますでしょうか？
・コードのインデントを修正：スペース4に変更し修正しました。

＜未完成＞
・レスポンシブの修正がまだできていないです。
　こちら少しお時間をいただいても良いでしょうか？
　お待たせして申し訳ないです。

ご多忙の中恐縮ですが、上記ご確認をよろしくお願いいたします。

2021-02-27 09:59 UTC, Akrjourney commented
Providerを削除するのを忘れていました。
削除後再度pushしております。

2021-02-28 01:53 UTC, quest-academia requested changes
修正ありがとうございます。
マイグレーション・シーダーファイル修正など、完璧です！

VSコードのフォーマッターを使ってインデントなどを調整して頂いたんですね！
ありがとうございます😊

いくつかインデントなどで修正頂きたい点がありましたので、
コメントご確認の上ご修正いただけたら幸いです！

宜しくお願い致します❗️

2021-02-28 01:53 UTC, quest-academia commented on app/Http/Controllers/PostsController.php
> +
修正ありがとうございます！

インデント修正に関して、せっかくやって頂いたのに申し訳ないですが、
ここのインデントは今のままのスペース４つ分でOKですよ。

今の形だと、メソッド内のインデントが消えてしまっています。

お手数ですが、これ以外のコントローラも含めて全体的に
インデントを再度修正いただけますでしょうか・・・？

2021-02-28 01:53 UTC, quest-academia commented on app/Http/Controllers/PostsController.php
> +    $validator = Validator::make($request->all() , ['title' => 'required|max:50', 'body' => 'required|max:255']);
めちゃ細かいですが、コーディング規約的に、
ここのカンマの前のスペースは不要ですね！

`$request->all() ,`
ではなく、
`$request->all(),`

にしましょう！

2021-02-28 01:53 UTC, quest-academia commented on resources/views/auth/login.blade.php
> +                        @endsection
細かいですが、
ここも全て、インデントでスペース４つ分減らすのが正しいですね。

2021-02-28 01:53 UTC, quest-academia commented on resources/views/auth/register.blade.php
> +                    @endsection
細かいですが、
ここも全て、インデントでスペース４つ分減らすのが正しいですね。

2021-02-28 01:53 UTC, quest-academia commented on resources/views/post/edit.blade.php
>              </div>
細かいですが、
ここも全て、インデント４つ分減らすのが正しいですね。

2021-02-28 01:53 UTC, quest-academia commented on resources/views/post/index.blade.php
> +                            @else
ここは、インデント８つ分減らすのが正しいですね。

2021-02-28 01:53 UTC, quest-academia commented on resources/views/post/index.blade.php
> +                            @endif
ここは、インデント８つ分減らすのが正しいですね。

2021-02-28 01:53 UTC, quest-academia commented on resources/views/post/new.blade.php
> +    ß@endsection
この
`ß`
は不要じゃないでしょうか？

2021-02-28 01:53 UTC, quest-academia commented on resources/views/user/edit.blade.php
> +        @endsection
このファイル、最後の
@endsection
の位置がおかしいので、
全体的にインデントが誤っていないでしょうか？

2021-02-28 01:53 UTC, quest-academia commented on resources/views/user/show.blade.php
> +                    @endsection
このファイルも、最後の
`@endsection`
の位置がおかしいので、
全体的にインデントが誤っていないでしょうか？

2021-03-06 22:59 UTC, Akrjourney commented
修正が遅くなってすみません。

全体的にインデントを修正いたしました。
親要素に合うように、閉じタグを改行したり、他ズレている部分は全体的に修正しています。

もしかすると間違えている箇所もまだあるかもしれないので、お手数ですが再度ご確認をお願いできればと思います。
よろしくお願いいたします。

2021-03-06 23:15 UTC, quest-academia commented on app/Comment.php
>      'comment'
ここ、インデントが必要になりますね。

2021-03-06 23:31 UTC, quest-academia requested changes
確認しました！
前より良くなりましたね😊

リファクタリングは今後の実務でも非常に大事な要素なので
是非この機会にコーディング規約PSR-2をざっと覚えましょう！

いくつか、修正頂きたい点がありますので修正お願いします。

今回は僕の方でブラウザ上で動作確認はしていませんが
次回の修正ができたら、僕の方でも動作確認しようと思います。

Akariさんの方でも、次回プッシュ前には全体の動作確認をしておいて下さい！
（今回の修正で動作がおかしくなった可能性もありえますので）

宜しくおねがい致します❗️

2021-03-06 23:31 UTC, quest-academia commented on app/Comment.php
>      return $this->belongsTo('App\User');
ここも、インデントが必要になりますね。

2021-03-06 23:31 UTC, quest-academia commented on app/Comment.php
>      return $this->belongsTo('App\Post');
ここも、インデントが必要になりますね。

2021-03-06 23:31 UTC, quest-academia commented on app/Http/Controllers/PostsController.php
> +    }
こちら、インデントが付いていないのと
カッコの位置もPSR-2基準に合致していません。
よく見直して、下記のように書きましょう！

```
if ($validator->fails()) {
     return redirect()->back()->withErrors($validator->errors())->withInput();
}
```

2021-03-06 23:31 UTC, quest-academia commented on app/Http/Controllers/PostsController.php
> +        'post' => $post,
ここも、インデントが必要になりますね。

2021-03-06 23:31 UTC, quest-academia commented on app/Http/Controllers/PostsController.php
>          'body' => 'required|max:250',
ここも、インデントが必要になりますね。

2021-03-06 23:31 UTC, quest-academia commented on app/Http/Controllers/UsersController.php
> +
ここだけではなく、全体的にですが、
メソッドの開始と終了位置に空行は不要です！

実務でもあまり歓迎されないと思いますので、
可能であれば全体的に開始と終了位置の空行は削除しましょう😊

2021-03-06 23:31 UTC, quest-academia commented on app/Http/Controllers/UsersController.php
> +    ]);
ここも、インデントが必要になりますね。

2021-03-06 23:31 UTC, quest-academia commented on app/Http/Controllers/UsersController.php
>      }
こちら、インデントが付いていないのと
カッコの位置もPSR-2基準に合致していません。
よく見直して、下記のように書きましょう！

```
if ($validator->fails()) {
}
```

また、{} の中の、前後の空行も不要ですね。

2021-03-13 10:20 UTC, Akrjourney commented
遅くなってすみません。
コードを再度修正しております。
デバッグも完了しております。

2021-03-13 22:37 UTC, SekiYukihiro requested changes
修正ありがとうございました！！

インデントについてはかなり良くなったと思いますが、いくつか対応漏れがありましたので、
GitHubでインデントについてコメントしましたので、その部分を修正お願いします！

また、僕の方でデバッグしていて、処理が上手くいかない部分をいくつか見つけました。
実務でもそうだと思いますが、デバッグはしっかり行うようにしましょうね😊

デバッグで見つけたポイントは、下記に書きます。

①新規投稿画面と投稿編集画面で、
　タイトル文字数上限を超えてバリデーションエラーが発生した場合、タイトルが消えてしまう
　→new.blade.phpと、edit.blade.phpに
`　　{{ old('title') }}　`
　　を追加しましょう。

②新規投稿画面の「投稿する」ボタンの高さが下に寄りすぎている
　→　投稿編集画面のボタン位置と合わせましょう！

③プロフィール編集時、メールアドレスを変えないと編集できない（バリデーションエラーとなる）。
下記のように書き換えれば、自分のメールアドレスの重複チェックが省けると思います。

●参考記事
https://biz.addisteria.com/unique_validation/

```
UsersController
（前略）

use Illuminate\Validation\Rule; // ←追記

（中略）

public function update(User $user, Request $request) // ←パラメータで$user情報を持ってくるようにViewやルーターも含めて変更しないといけません
    {
        $validator = Validator::make($request->all() , [
            'name' => 'required|string|max:20',
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($user->id)],
            'password' => 'required|string|min:6|confirmed',
    ]);
```

④ログイン・新規登録画面のレスポンシブ対応は、まだされていないでしょうか？
　これは急ぎませんが、また対応いただけると助かります🙇‍♂️


お手数ですが、宜しくお願い致します！

2021-03-21 02:30 UTC, Akrjourney commented
遅くなってすみません。
ご指摘をいただいた部分を修正したのですが、またご確認をお願いできますでしょうか。

レスポンシブ対応できるよう、デザインも修正しました。
ユーザープロフィール画面ですが、前回のコーディングではスマホ表示になるとフォームが大きく崩れて見辛かったので、少しデザインを変えています。（添付画像参照）
新規登録画面、ログイン画面はグリッドシステムを調整してレスポンシブ対応できるようにしています。

![Screen Shot 2021-03-21 at 11 07 20 AM](https://user-images.githubusercontent.com/68174453/111891781-cb630d00-8a38-11eb-83b1-a2283a4d8406.png)

2021-03-22 06:24 UTC, Akrjourney commented
投稿編集画面のバリデーションを修正いたしました。
仰る通り、アドバイスいただいたコードで修正できました。
有難うございます。

他にも気になる点はございますでしょうか？

2021-03-24 08:41 UTC, SekiYukihiro approved these changes

2021-03-24 08:41 UTC, SekiYukihiro commented
OKです

2021-03-24 20:55 UTC, quest-academia approved these changes
OKです！
確認完了しましたので、マージしました。

お疲れ様でした😊

2021-03-24 20:56 UTC, merged